### ISSUE TITLE
Koodikatselmointi v2

### ISSUE THREAD

**Issue by jehie** [Pulperi/MLG-360-NOSCOPE-SUDOKU-SOLVER#1]
Ladattu 24.2.2015 - klo 15.00

Hei!

Ohjelmasi näyttää hyvältä! Visuaalinen käyttöliittymä on selkeä ja kaikki näyttää toimivan. Sudokujen tallennusnappi näyttää vain puuttuvan :).  Käyttöliittymän kokoa voisi myös vähän säätää, nyt ainakin itselläni näkyy runsaasti turhia reunoja.  Sudokujen avaamiseen käytettyyn File Chooseriin voisi lisätä sen että se näyttää vain halutut tiedostopäätteet, eikä kaikkia. 

Kirjoittamasi koodi vaikuttaa erittäin selkeältä. Koodin seassa olevat selkeät kommentit tekevät koodin lukemisesta helppoa. SudokuGenerator-luokan metodit ovat kenties vähän vaikeaselkoisia, toisaalta private-metodeja ei ulkopuolisen välttämättä tarvitse sen tarkemmin ymmärtää.  Luokkien ja pakettien nimet ovat järkeviä ja kuvaavat hyvin niiden sisältöä. Luokka Coords voisi olla oma erillinen tiedosto, eikä SudoguGenerator- luokan sisällä piilossa.  Aihemäärittely ja muut dokumentit ovat ajan tasalla ja selkeitä. 

Testien kattavuus on erinomaista ja mutanttejakin on tapettu hyvin. Testit näyttävät myös järkeviltä ja kattavilta sekä menevät läpi. JavaDoc vaikuttaa erinomaiselta ja kattavalta. SudokuGenerator luokan kuvaus on kenties vähän oudon näköinen. 

Mielestäni koodisi noudattaa hyvin aiemmilla kursseilla opittuja käytänteitä sekä Clean code-periaatetta. Hauska lisä olisi jos sudokuja voisi täyttää käyttöliittymällä tai vaikka printata ulos ohjelmasta. 

Tsemppiä ohjelman viimeistelyyn!

**Comment by Pulperi** [comment]
Moi Jehie,

Kiitti kommenteista. Tuo tiedostofiltteri tuohon file chooseriin olikin hyvä idea. Lisäsin tänään joutessani.
Lisäsin myös tuon mainitsemasi "pelimoodin" eli siis generoituja/vielä ratkaisemattomia sudokuja pääsee nyt täyttelemään käyttöliittymällä. Saa koittaa jos kiinnostaa. ;)

Allekirjoitan kyllä tuon kommenttisi joidenkin metodien monimutkaisuudesta. Olen kyllä koittanut pilkkoa niitä, niiltä osin mikä on tuntunut järkevältä, mutta osa algoritmeista on vain niin monimutkaisia.
